### PR TITLE
Switch to rxphp 2

### PR DESCRIPTION
**Pull request by Vinceveve**
Adapt code and example to use reactivex php 2.0

await can be useful sometimes :)

### CODE REVIEW

**Comment by Vinceveve** [comment]
The build is crashed because of the build (php compat and phpunit compat with defined images)

**Comment by davidwdan** [comment]
If you require `voryx/event-loop` v2.0, it'll bootstrap the event loop scheduler for you.

You'll also need to bump up the php deps to 7.1+

**Comment by Vinceveve** [comment]
Thanks a lot @davidwdan !

**Comment by davidwdan** [comment]
No Problem.

**Pull request merged**
